# Generated by Django 3.2.7 on 2022-01-02 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Artisan_app', '0002_userform_password2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userform',
            name='username',
            field=models.CharField(max_length=100),
        ),
    ]
